""" A test derived exception."""

from .custom_error import CustomError

class CustomDerivedError(CustomError):
    """A test derived exception"""
    pass